// ejerciciosSinResolver/Curso JS Moderno/55-cotizadorPrestamosVue/src/components/Button.vue
<script setup>
  const props = defineProps({
    operador: String,
    fn: Function
  });
</script>

<template>
  <button
    type="button"
    class="h-10 w-10 flex items-center justify-center font-bold bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl"
    @click="$emit('fn')"
  >{{ operador }}</button>
</template>

// ejerciciosSinResolver/Curso JS Moderno/54-cotizadorPrestamosReact/src/components/Button.jsx
/* eslint-disable react/prop-types */
function Button({operador, fn}) {

  return (
    <button
        type='button'
        className='h-10 w-10 flex items-start justify-center font-bold text-white text-2xl bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500'
        onClick={fn}
    >{operador}</button>
  )
}

export default Button
